export const TeamColors = [
    { name: 'Philadelphia Warriors', color: '#13299F' },
    { name: 'Baltimore Bullets', color: '#D77800' },
    { name: 'Minneapolis Lakers', color: '#FCEA04' },
    { name: 'Rochester Royals', color: '#2C0061' },
    { name: 'Syracuse Nationals', color: '#336699' },
    { name: 'Boston Celtics', color: '#007A33' },
    { name: 'Cincinatti Royals', color: '#CC3527' },
    { name: 'St. Louis Hawks', color: '#AD314F' },
    { name: 'Los Angeles Lakers', color: '#552583' },
    { name: 'Philadelphia 76ers', color: '#006BB6' },
    { name: 'Atlanta Hawks', color: '#E03A3E' },
    { name: 'New York Knicks', color: '#006BB6' },
    { name: 'Milwaukee Bucks', color: '#00471B' },
    { name: 'Golden State Warriors', color: '#1D428A' },
    { name: 'Kansas City Kings', color: '#CC3527' },
    { name: 'Sacramento Kings', color: '#5A2D81' },
    { name: 'Portland Trail Blazers', color: '#E03A3E' },
    { name: 'Washington Bullets', color: '#002B5C' },
    { name: 'Seattle SuperSonics', color: '#00653A' },
    { name: 'Detroit Pistons', color: '#C8102E' },
    { name: 'Chicago Bulls', color: '#CE1141' },
    { name: 'Houston Rockets', color: '#CE1141' },
    { name: 'Washington Wizards', color: '#002B5C' },
    { name: 'San Antonio Spurs', color: '#C4CED4' },
    { name: 'Miami Heat', color: '#98002E' },
    { name: 'Oklahoma City Thunder', color: '#007AC1' },
    { name: 'Dallas Mavericks', color: '#00538C' },
    { name: 'Cleveland Cavaliers', color: '#860038' },
    { name: 'Toronto Raptors', color: '#CE1141' },
];

// https://teamcolorcodes.com/nba-team-color-codes/